"""Entrypoint."""

from langchain_core.messages import HumanMessage

from chat_bot import chat_bot_chain


def get_response_from_bot(user_message: str) -> str:
    """
    Generate a response from the chatbot based on the user's message.

    Args:
        user_message (str): The message input from the user.

    Returns:
        str: The response generated by the chatbot.
    """
    response = chat_bot_chain.invoke({"history": [HumanMessage(content=user_message)]})
    return response.content


if __name__ == "__main__":
    print("BOT: Hi, I know all about cats!")

    while True:
        user_message = input("YOU: ")
        print(f"BOT: {get_response_from_bot(user_message)}")
